# Generated by Django 3.0.4 on 2020-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30, verbose_name='First Name')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('dateJoined', models.DateField(verbose_name='Date Joined')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePlayed', models.DateField(verbose_name='Date Played')),
                ('scoreOne', models.SmallIntegerField(verbose_name="First Player's Score")),
                ('scoreTwo', models.SmallIntegerField(verbose_name="Second Player's Score")),
                ('players', models.ManyToManyField(to='scrabbler_app.Profile')),
            ],
        ),
    ]
