# Generated by Django 3.0.4 on 2020-03-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabbler_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreOne', models.SmallIntegerField(verbose_name="Player 1's Score")),
                ('scoreTwo', models.SmallIntegerField(verbose_name="Player 2's Score")),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='scoreOne',
        ),
        migrations.RemoveField(
            model_name='match',
            name='scoreTwo',
        ),
        migrations.AddField(
            model_name='match',
            name='scores',
            field=models.ManyToManyField(to='scrabbler_app.Score'),
        ),
    ]
