# Generated by Django 3.0.4 on 2020-03-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrabbler_app', '0002_auto_20200327_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='scores',
        ),
        migrations.AddField(
            model_name='match',
            name='scores',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='scrabbler_app.Score'),
            preserve_default=False,
        ),
    ]
