# Generated by Django 3.0.4 on 2020-03-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrabbler_app', '0004_auto_20200327_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='scores',
        ),
        migrations.AddField(
            model_name='score',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scrabbler_app.Profile'),
            preserve_default=False,
        ),
    ]
