# Generated by Django 3.0.4 on 2020-03-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabbler_app', '0005_auto_20200327_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='won',
            field=models.BooleanField(default=True, verbose_name='Player won?'),
            preserve_default=False,
        ),
    ]
