# Generated by Django 3.0.4 on 2021-05-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabbler_app', '0006_score_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dateJoined',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='won',
        ),
        migrations.AddField(
            model_name='match',
            name='noOfPlayers',
            field=models.IntegerField(default=2, verbose_name='Number of Players'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='test', max_length=30, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='points',
            field=models.SmallIntegerField(default=0, verbose_name='Points'),
            preserve_default=False,
        ),
    ]
