# Generated by Django 3.0.4 on 2021-05-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabbler_app', '0007_auto_20210515_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(default='Ciaran', max_length=30, verbose_name='Match Winner'),
            preserve_default=False,
        ),
    ]
