# Generated by Django 4.1.7 on 2023-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabbler_app', '0009_score_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='forename',
            field=models.CharField(default='Test', max_length=30, verbose_name='Forename'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='Test', max_length=30, verbose_name='Surname'),
            preserve_default=False,
        ),
    ]
