# Generated by Django 4.1.7 on 2023-02-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabbler_app', '0011_matchscore_player_remove_score_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchscore',
            name='score',
            field=models.SmallIntegerField(verbose_name='Score'),
        ),
    ]
