# Generated by Django 4.1.7 on 2023-02-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabbler_app', '0012_alter_matchscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscore',
            name='won',
            field=models.BooleanField(default=False, verbose_name='Won'),
        ),
    ]
